### ISSUE TITLE
Please update readme with correct apigee links

### ISSUE THREAD

**Issue by tkachenkoas** [WhiteHouse/api-standards#58]
http://apigee.com/about/resources/ebooks/api-fa%C3%A7ade-pattern -> https://pages.apigee.com/rs/apigee/images/api-facade-pattern-ebook-2012-06.pdf
http://pages.apigee.com/web-api-design-ebook.html -> https://pages.apigee.com/rs/apigee/images/api-design-ebook-2012-03.pdf

**Comment by danielbom** [comment]
The maintainers of this project are not available. Take a look into "pull requests", the last updates requested to update links were not accepted.

**Comment by tkachenkoas** [comment]
Oh, I see... pity ;(
